before_script:
    - apk add --no-cache python3 py3-pip chromium chromium-chromedriver
    - python3 -m venv twidder
    - source twidder/bin/activate
    - pip install -r requirements.txt

run tests:
    stage: test
    script:
        - uname -a
        - python -m pytest
