before_script:
    - apk add --no-cache python3 py3-pip
    - python3 -m venv app_env
    - source app_env/bin/activate
    - pip install -r requirements.txt

run tests:
    stage: test
    script:
        - python -m pytest
