before_script:
    - apt-get install firefox-geckodriver
    - apk add --no-cache python3 py3-pip
    - python3 -m venv twidder
    - source twidder/bin/activate
    - pip install -r requirements.txt

run tests:
    stage: test
    script:
        - python -m pytest
